const localizedBooks: Record<string, string[]> = {
  en: [
    "Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy",
    "Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel",
    "1 Kings", "2 Kings", "1 Chronicles", "2 Chronicles", "Ezra",
    "Nehemiah", "Esther", "Job", "Psalms", "Proverbs",
    "Ecclesiastes", "Song of Solomon", "Isaiah", "Jeremiah", "Lamentations",
    "Ezekiel", "Daniel", "Hosea", "Joel", "Amos",
    "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk",
    "Zephaniah", "Haggai", "Zechariah", "Malachi", "Matthew",
    "Mark", "Luke", "John", "Acts", "Romans",
    "1 Corinthians", "2 Corinthians", "Galatians", "Ephesians", "Philippians",
    "Colossians", "1 Thessalonians", "2 Thessalonians", "1 Timothy", "2 Timothy",
    "Titus", "Philemon", "Hebrews", "James", "1 Peter",
    "2 Peter", "1 John", "2 John", "3 John", "Jude",
    "Revelation"
  ],
  af: [
    "Genesis", "Eksodus", "Levitikus", "Numeri", "Deuteronomium",
    "Josua", "Rigters", "Rut", "1 Samuel", "2 Samuel",
    "1 Konings", "2 Konings", "1 Kronieke", "2 Kronieke", "Esra",
    "Nehemia", "Ester", "Job", "Psalms", "Spreuke",
    "Prediker", "Hooglied", "Jesaja", "Jeremia", "Klaagliedere",
    "Esegiël", "Daniël", "Hosea", "Joël", "Amos",
    "Obadja", "Jona", "Miga", "Nahum", "Habakuk",
    "Sefanja", "Haggai", "Sagaria", "Maleagi", "Matteus",
    "Markus", "Lukas", "Johannes", "Handelinge", "Romeine",
    "1 Korintiërs", "2 Korintiërs", "Galasiërs", "Efesiërs", "Filippense",
    "Kolossense", "1 Tessalonisense", "2 Tessalonisense", "1 Timoteus", "2 Timoteus",
    "Titus", "Filemon", "Hebreërs", "Jakobus", "1 Petrus",
    "2 Petrus", "1 Johannes", "2 Johannes", "3 Johannes", "Judas",
    "Openbaring"
  ],
  ar: [
    "تكوين", "خروج", "لاويين", "عدد", "تثنية",
    "يشوع", "قضاة", "راعوث", "1 صموئيل", "2 صموئيل",
    "1 ملوك", "2 ملوك", "1 أخبار", "2 أخبار", "عزرا",
    "نحميا", "أستير", "أيوب", "مزامير", "أمثال",
    "جامعة", "نشيد الأنشاد", "إشعياء", "إرميا", "مراثي إرميا",
    "حزقيال", "دانيال", "هوشع", "يوئيل", "عاموس",
    "عوبديا", "يونان", "ميخا", "ناحوم", "حبقوق",
    "صفنيا", "حجي", "زكريا", "ملاخي", "متى",
    "مرقس", "لوقا", "يوحنا", "أعمال", "رومية",
    "1 كورنثوس", "2 كورنثوس", "غلاطية", "أفسس", "فيلبي",
    "كولوسي", "1 تسالونيكي", "2 تسالونيكي", "1 تيموثاوس", "2 تيموثاوس",
    "تيتوس", "فليمون", "عبرانيين", "يعقوب", "1 بطرس",
    "2 بطرس", "1 يوحنا", "2 يوحنا", "3 يوحنا", "يهوذا",
    "رؤيا"
  ],
  de: [
    "1. Mose", "2. Mose", "3. Mose", "4. Mose", "5. Mose",
    "Josua", "Richter", "Rut", "1. Samuel", "2. Samuel",
    "1. Könige", "2. Könige", "1. Chronik", "2. Chronik", "Esra",
    "Nehemia", "Esther", "Hiob", "Psalmen", "Sprüche",
    "Prediger", "Hohelied", "Jesaja", "Jeremia", "Klagelieder",
    "Hesekiel", "Daniel", "Hosea", "Joel", "Amos",
    "Obadja", "Jona", "Micha", "Nahum", "Habakuk",
    "Zephanja", "Haggai", "Sacharja", "Maleachi", "Matthäus",
    "Markus", "Lukas", "Johannes", "Apostelgeschichte", "Römer",
    "1. Korinther", "2. Korinther", "Galater", "Epheser", "Philipper",
    "Kolosser", "1. Thessalonicher", "2. Thessalonicher", "1. Timotheus", "2. Timotheus",
    "Titus", "Philemon", "Hebräer", "Jakobus", "1. Petrus",
    "2. Petrus", "1. Johannes", "2. Johannes", "3. Johannes", "Judas",
    "Offenbarung"
  ],
  es: [
    "Génesis", "Éxodo", "Levítico", "Números", "Deuteronomio",
    "Josué", "Jueces", "Rut", "1 Samuel", "2 Samuel",
    "1 Reyes", "2 Reyes", "1 Crónicas", "2 Crónicas", "Esdras",
    "Nehemías", "Ester", "Job", "Salmos", "Proverbios",
    "Eclesiastés", "Cantares", "Isaías", "Jeremías", "Lamentaciones",
    "Ezequiel", "Daniel", "Oseas", "Joel", "Amós",
    "Abdías", "Jonás", "Miqueas", "Nahum", "Habacuc",
    "Sofonías", "Hageo", "Zacarías", "Malaquías", "Mateo",
    "Marcos", "Lucas", "Juan", "Hechos", "Romanos",
    "1 Corintios", "2 Corintios", "Gálatas", "Efesios", "Filipenses",
    "Colosenses", "1 Tesalonicenses", "2 Tesalonicenses", "1 Timoteo", "2 Timoteo",
    "Tito", "Filemón", "Hebreos", "Santiago", "1 Pedro",
    "2 Pedro", "1 Juan", "2 Juan", "3 Juan", "Judas",
    "Apocalipsis"
  ],
  fi: [
    "1. Mooseksen kirja", "2. Mooseksen kirja", "3. Mooseksen kirja", "4. Mooseksen kirja", "5. Mooseksen kirja",
    "Joosua", "Tuomarien kirja", "Ruutin kirja", "1. Samuelin kirja", "2. Samuelin kirja",
    "1. Kuninkaiden kirja", "2. Kuninkaiden kirja", "1. Aikakirja", "2. Aikakirja", "Esran kirja",
    "Nehemian kirja", "Esterin kirja", "Jobin kirja", "Psalmit", "Sananlaskut",
    "Saarnaaja", "Laulujen laulu", "Jesajan kirja", "Jeremian kirja", "Valitusvirret",
    "Hesekielin kirja", "Danielin kirja", "Hoosean kirja", "Joelin kirja", "Aamoksen kirja",
    "Obadjan kirja", "Joonan kirja", "Miikan kirja", "Nahumin kirja", "Habakukin kirja",
    "Sefanjan kirja", "Haggain kirja", "Sakarjan kirja", "Malakian kirja", "Matteuksen evankeliumi",
    "Markuksen evankeliumi", "Luukkaan evankeliumi", "Johanneksen evankeliumi", "Apostolien teot", "Roomalaiskirje",
    "1. Korinttolaiskirje", "2. Korinttolaiskirje", "Galatalaiskirje", "Efesolaiskirje", "Filippiläiskirje",
    "Kolossalaiskirje", "1. Tessalonikalaiskirje", "2. Tessalonikalaiskirje", "1. Timoteuskirje", "2. Timoteuskirje",
    "Tiituksen kirje", "Filemonin kirje", "Heprealaiskirje", "Jaakobin kirje", "1. Pietarin kirje",
    "2. Pietarin kirje", "1. Johanneksen kirje", "2. Johanneksen kirje", "3. Johanneksen kirje", "Juudaksen kirje",
    "Johanneksen ilmestys"
  ],
  fr: [
    "Genèse", "Exode", "Lévitique", "Nombres", "Deutéronome",
    "Josué", "Juges", "Ruth", "1 Samuel", "2 Samuel",
    "1 Rois", "2 Rois", "1 Chroniques", "2 Chroniques", "Esdras",
    "Néhémie", "Esther", "Job", "Psaumes", "Proverbes",
    "Ecclésiaste", "Cantique des Cantiques", "Ésaïe", "Jérémie", "Lamentations",
    "Ézéchiel", "Daniel", "Osée", "Joël", "Amos",
    "Abdias", "Jonas", "Michée", "Nahum", "Habacuc",
    "Sophonie", "Aggée", "Zacharie", "Malachie", "Matthieu",
    "Marc", "Luc", "Jean", "Actes", "Romains",
    "1 Corinthiens", "2 Corinthiens", "Galates", "Éphésiens", "Philippiens",
    "Colossiens", "1 Thessaloniciens", "2 Thessaloniciens", "1 Timothée", "2 Timothée",
    "Tite", "Philémon", "Hébreux", "Jacques", "1 Pierre",
    "2 Pierre", "1 Jean", "2 Jean", "3 Jean", "Jude",
    "Apocalypse"
  ],
  he: [
    "בראשית", "שמות", "ויקרא", "במדבר", "דברים",
    "יהושע", "שופטים", "רות", "שמואל א", "שמואל ב",
    "מלכים א", "מלכים ב", "דברי הימים א", "דברי הימים ב", "עזרא",
    "נחמיה", "אסתר", "איוב", "תהלים", "משלי",
    "קהלת", "שיר השירים", "ישעיהו", "ירמיהו", "איכה",
    "יחזקאל", "דניאל", "הושע", "יואל", "עמוס",
    "עובדיה", "יונה", "מיכה", "נחום", "חבקוק",
    "צפניה", "חגי", "זכריה", "מלאכי", "מתי",
    "מרקוס", "לוקס", "יוחנן", "מעשי השליחים", "אל הרומים",
    "1 אל הקורינתים", "2 אל הקורינתים", "אל הגלטים", "אל האפסים", "אל הפיליפים",
    "אל הקולוסים", "1 אל התסלוניקים", "2 אל התסלוניקים", "1 אל טימותיוס", "2 אל טימותיוס",
    "אל טיטוס", "אל פילימון", "אל העברים", "אגרת יעקב", "1 כיפא",
    "2 כיפא", "1 יוחנן", "2 יוחנן", "3 יוחנן", "אגרת יהודה",
    "חזון יוחנן"
  ],
  hi: [
    "उत्पत्ति", "निर्गमन", "लैव्यव्यवस्था", "गिनती", "व्यवस्थाविवरण",
    "यहोशू", "न्यायियों", "रूत", "1 शमूएल", "2 शमूएल",
    "1 राजा", "2 राजा", "1 इतिहास", "2 इतिहास", "एज्रा",
    "नहेम्याह", "एस्तेर", "अय्यूब", "भजन संहिता", "नीतिवचन",
    "सभोपदेशक", "श्रेष्ठगीत", "यशायाह", "यिर्मयाह", "विलापगीत",
    "यहेजकेल", "दानिय्येल", "होशे", "योएल", "आमोस",
    "ओबद्याह", "योना", "मीका", "नहूम", "हबक्कूक",
    "सपन्याह", "हाग्गै", "जकर्याह", "मलाकी", "मत्ती",
    "मरकुस", "लूका", "यूहन्ना", "प्रेरितों के काम", "रोमियों",
    "1 कुरिन्थियों", "2 कुरिन्थियों", "गलातियों", "इफिसियों", "फिलिप्पियों",
    "कुलुस्सियों", "1 थिस्सलुनीकियों", "2 थिस्सलुनीकियों", "1 तीमुथियुस", "2 तीमुथियुस",
    "तीतुस", "फिलेमोन", "इब्रानियों", "याकूब", "1 पतरस",
    "2 पतरस", "1 यूहन्ना", "2 यूहन्ना", "3 यूहन्ना", "यहूदा",
    "प्रकाशितवाक्य"
  ],
  id: [
    "Kejadian", "Keluaran", "Imamat", "Bilangan", "Ulangan",
    "Yosua", "Hakim-hakim", "Rut", "1 Samuel", "2 Samuel",
    "1 Raja-raja", "2 Raja-raja", "1 Tawarikh", "2 Tawarikh", "Ezra",
    "Nehemia", "Ester", "Ayub", "Mazmur", "Amsal",
    "Pengkhotbah", "Kidung Agung", "Yesaya", "Yeremia", "Ratapan",
    "Yehezkiel", "Daniel", "Hosea", "Yoel", "Amos",
    "Obaja", "Yunus", "Mikha", "Nahum", "Habakuk",
    "Zefanya", "Hagai", "Zakharia", "Maleakhi", "Matius",
    "Markus", "Lukas", "Yohanes", "Kisah Para Rasul", "Roma",
    "1 Korintus", "2 Korintus", "Galatia", "Efesus", "Filipi",
    "Kolose", "1 Tesalonika", "2 Tesalonika", "1 Timotius", "2 Timotius",
    "Titus", "Filemon", "Ibrani", "Yakobus", "1 Petrus",
    "2 Petrus", "1 Yohanes", "2 Yohanes", "3 Yohanes", "Yudas",
    "Wahyu"
  ],
  it: [
    "Genesi", "Esodo", "Levitico", "Numeri", "Deuteronomio",
    "Giosuè", "Giudici", "Rut", "1 Samuele", "2 Samuele",
    "1 Re", "2 Re", "1 Cronache", "2 Cronache", "Esdra",
    "Neemia", "Ester", "Giobbe", "Salmi", "Proverbi",
    "Ecclesiaste", "Cantico dei Cantici", "Isaia", "Geremia", "Lamentazioni",
    "Ezechiele", "Daniele", "Osea", "Gioele", "Amos",
    "Abdia", "Giona", "Michea", "Naum", "Abacuc",
    "Sofonia", "Aggeo", "Zaccaria", "Malachia", "Matteo",
    "Marco", "Luca", "Giovanni", "Atti", "Romani",
    "1 Corinzi", "2 Corinzi", "Galati", "Efesini", "Filippesi",
    "Colossesi", "1 Tessalonicesi", "2 Tessalonicesi", "1 Timoteo", "2 Timoteo",
    "Tito", "Filemone", "Ebrei", "Giacomo", "1 Pietro",
    "2 Pietro", "1 Giovanni", "2 Giovanni", "3 Giovanni", "Giuda",
    "Apocalisse"
  ],
  ja: [
    "創世記", "出エジプト記", "レビ記", "民数記", "申命記",
    "ヨシュア記", "士師記", "ルツ記", "サムエル記上", "サムエル記下",
    "列王記上", "列王記下", "歴代志上", "歴代志下", "エズラ記",
    "ネヘミヤ記", "エステル記", "ヨブ記", "詩篇", "箴言",
    "伝道者の書", "雅歌", "イザヤ書", "エレミヤ書", "哀歌",
    "エゼキエル書", "ダニエル書", "ホセア書", "ヨエル書", "アモス書",
    "オバデヤ書", "ヨナ書", "ミカ書", "ナホム書", "ハバクク書",
    "ゼパニヤ書", "ハガイ書", "ゼカリヤ書", "マラキ書", "マタイの福音書",
    "マルコの福音書", "ルカの福音書", "ヨハネの福音書", "使徒の働き", "ローマ人への手紙",
    "コリント人への手紙第一", "コリント人への手紙第二", "ガラテヤ人への手紙", "エペソ人への手紙", "ピリピ人への手紙",
    "コロサイ人への手紙", "テサロニケ人への手紙第一", "テサロニケ人への手紙第二", "テモテへの手紙第一", "テモテへの手紙第二",
    "テトスへの手紙", "ピレモンへの手紙", "ヘブル人への手紙", "ヤコブの手紙", "ペテロの手紙第一",
    "ペテロの手紙第二", "ヨハネの手紙第一", "ヨハネの手紙第二", "ヨハネの手紙第三", "ユダの手紙",
    "ヨハネの黙示録"
  ],
  nl: [
    "Genesis", "Exodus", "Leviticus", "Numeri", "Deuteronomium",
    "Jozua", "Rechters", "Ruth", "1 Samuel", "2 Samuel",
    "1 Koningen", "2 Koningen", "1 Kronieken", "2 Kronieken", "Ezra",
    "Nehemia", "Esther", "Job", "Psalmen", "Spreuken",
    "Prediker", "Hooglied", "Jesaja", "Jeremia", "Klaagliederen",
    "Ezechiël", "Daniël", "Hosea", "Joël", "Amos",
    "Obadja", "Jona", "Micha", "Nahum", "Habakuk",
    "Zefanja", "Haggai", "Zacharia", "Maleachi", "Matteüs",
    "Marcus", "Lucas", "Johannes", "Handelingen", "Romeinen",
    "1 Korintiërs", "2 Korintiërs", "Galaten", "Efeziërs", "Filippenzen",
    "Kolossenzen", "1 Tessalonicenzen", "2 Tessalonicenzen", "1 Timoteüs", "2 Timoteüs",
    "Titus", "Filemon", "Hebreeën", "Jakobus", "1 Petrus",
    "2 Petrus", "1 Johannes", "2 Johannes", "3 Johannes", "Judas",
    "Openbaring"
  ],
  pl: [
    "Księga Rodzaju", "Księga Wyjścia", "Księga Kapłańska", "Księga Liczb", "Księga Powtórzonego Prawa",
    "Księga Jozuego", "Księga Sędziów", "Księga Rut", "1 Księga Samuela", "2 Księga Samuela",
    "1 Księga Królewska", "2 Księga Królewska", "1 Księga Kronik", "2 Księga Kronik", "Księga Ezdrasza",
    "Księga Nehemiasza", "Księga Estery", "Księga Hioba", "Księga Psalmów", "Księga Przysłów",
    "Księga Koheleta", "Pieśń nad Pieśniami", "Księga Izajasza", "Księga Jeremiasza", "Lamentacje",
    "Księga Ezechiela", "Księga Daniela", "Księga Ozeasza", "Księga Joela", "Księga Amosa",
    "Księga Abdiasza", "Księga Jonasza", "Księga Micheasza", "Księga Nahuma", "Księga Habakuka",
    "Księga Sofoniasza", "Księga Aggeusza", "Księga Zachariasza", "Księga Malachiasza", "Ewangelia Mateusza",
    "Ewangelia Marka", "Ewangelia Łukasza", "Ewangelia Jana", "Dzieje Apostolskie", "List do Rzymian",
    "1 List do Koryntian", "2 List do Koryntian", "List do Galatów", "List do Efezjan", "List do Filipian",
    "List do Kolosan", "1 List do Tesaloniczan", "2 List do Tesaloniczan", "1 List do Tymoteusza", "2 List do Tymoteusza",
    "List do Tytusa", "List do Filemona", "List do Hebrajczyków", "List Jakuba", "1 List Piotra",
    "2 List Piotra", "1 List Jana", "2 List Jana", "3 List Jana", "List Judy",
    "Apokalipsa św. Jana"
  ],
  pt: [
    "Gênesis", "Êxodo", "Levítico", "Números", "Deuteronômio",
    "Josué", "Juízes", "Rute", "1 Samuel", "2 Samuel",
    "1 Reis", "2 Reis", "1 Crônicas", "2 Crônicas", "Esdras",
    "Neemias", "Ester", "Jó", "Salmos", "Provérbios",
    "Eclesiastes", "Cânticos", "Isaías", "Jeremias", "Lamentações",
    "Ezequiel", "Daniel", "Oseias", "Joel", "Amós",
    "Obadias", "Jonas", "Miqueias", "Naum", "Habacuque",
    "Sofonias", "Ageu", "Zacarias", "Malaquias", "Mateus",
    "Marcos", "Lucas", "João", "Atos", "Romanos",
    "1 Coríntios", "2 Coríntios", "Gálatas", "Efésios", "Filipenses",
    "Colossenses", "1 Tessalonicenses", "2 Tessalonicenses", "1 Timóteo", "2 Timóteo",
    "Tito", "Filemom", "Hebreus", "Tiago", "1 Pedro",
    "2 Pedro", "1 João", "2 João", "3 João", "Judas",
    "Apocalipse"
  ],
  ro: [
    "Geneza", "Exodul", "Leviticul", "Numerii", "Deuteronomul",
    "Iosua", "Judecătorii", "Rut", "1 Samuel", "2 Samuel",
    "1 Regi", "2 Regi", "1 Cronici", "2 Cronici", "Ezra",
    "Neemia", "Estera", "Iov", "Psalmii", "Proverbe",
    "Eclesiastul", "Cântarea Cântărilor", "Isaia", "Ieremia", "Plângerile",
    "Ezechiel", "Daniel", "Osea", "Ioel", "Amos",
    "Obadia", "Iona", "Mica", "Naum", "Habacuc",
    "Țefania", "Hagai", "Zaharia", "Maleahi", "Matei",
    "Marcu", "Luca", "Ioan", "Faptele Apostolilor", "Romani",
    "1 Corinteni", "2 Corinteni", "Galateni", "Efeseni", "Filipeni",
    "Coloseni", "1 Tesaloniceni", "2 Tesaloniceni", "1 Timotei", "2 Timotei",
    "Tit", "Filimon", "Evrei", "Iacov", "1 Petru",
    "2 Petru", "1 Ioan", "2 Ioan", "3 Ioan", "Iuda",
    "Apocalipsa"
  ],
  ru: [
    "Бытие", "Исход", "Левит", "Числа", "Второзаконие",
    "Иисус Навин", "Книга Судей", "Книга Руфь", "1-я Царств", "2-я Царств",
    "3-я Царств", "4-я Царств", "1-я Паралипоменон", "2-я Паралипоменон", "Книга Ездры",
    "Книга Неемии", "Книга Есфири", "Книга Иова", "Псалтирь", "Книга Притчей",
    "Книга Екклесиаста", "Песнь Песней", "Книга Исаии", "Книга Иеремии", "Плач Иеремии",
    "Книга Иезекииля", "Книга Даниила", "Книга Осии", "Книга Иоиля", "Книга Амоса",
    "Книга Авдия", "Книга Ионы", "Книга Михея", "Книга Наума", "Книга Аввакума",
    "Книга Софонии", "Книга Аггея", "Книга Захарии", "Книга Малахии", "Евангелие от Матфея",
    "Евангелие от Марка", "Евангелие от Луки", "Евангелие от Иоанна", "Деяния апостолов", "Послание к Римлянам",
    "1-е послание к Коринфянам", "2-е послание к Коринфянам", "Послание к Галатам", "Послание к Ефесянам", "Послание к Филиппийцам",
    "Послание к Колоссянам", "1-е послание к Фессалоникийцам", "2-е послание к Фессалоникийцам", "1-е послание к Тимофею", "2-е послание к Тимофею",
    "Послание к Титу", "Послание к Филимону", "Послание к Евреям", "Послание Иакова", "1-е послание Петра",
    "2-е послание Петра", "1-е послание Иоанна", "2-е послание Иоанна", "3-е послание Иоанна", "Послание Иуды",
    "Откровение Иоанна Богослова"
  ],
  sw: [
    "Mwanzo", "Kutoka", "Mambo ya Walawi", "Hesabu", "Kumbukumbu la Torati",
    "Yoshua", "Waamuzi", "Ruthu", "1 Samweli", "2 Samweli",
    "1 Wafalme", "2 Wafalme", "1 Mambo ya Nyakati", "2 Mambo ya Nyakati", "Ezra",
    "Nehemia", "Esta", "Ayubu", "Zaburi", "Mithali",
    "Mhubiri", "Wimbo Ulio Bora", "Isaya", "Yeremia", "Maombolezo",
    "Ezekieli", "Danieli", "Hosea", "Yoeli", "Amosi",
    "Obadia", "Yona", "Mika", "Nahumu", "Habakuki",
    "Sefania", "Hagai", "Zekaria", "Malaki", "Mathayo",
    "Marko", "Luka", "Yohana", "Matendo", "Waroma",
    "1 Wakorintho", "2 Wakorintho", "Wagalatia", "Waefeso", "Wafilipi",
    "Wakolosai", "1 Wathesalonike", "2 Wathesalonike", "1 Timotheo", "2 Timotheo",
    "Tito", "Filemon", "Waebrania", "Yakobo", "1 Petro",
    "2 Petro", "1 Yohana", "2 Yohana", "3 Yohana", "Yuda",
    "Ufunuo"
  ],
  tl: [
    "Genesis", "Exodo", "Levitico", "Mga Bilang", "Deuteronomio",
    "Josue", "Mga Hukom", "Ruth", "1 Samuel", "2 Samuel",
    "1 Mga Hari", "2 Mga Hari", "1 Mga Kronika", "2 Mga Kronika", "Ezra",
    "Nehemias", "Ester", "Job", "Mga Awit", "Mga Kawikaan",
    "Ang Mangangaral", "Awit ni Solomon", "Isaias", "Jeremias", "Mga Panaghoy",
    "Ezekiel", "Daniel", "Oseas", "Joel", "Amos",
    "Obadias", "Jonas", "Mikas", "Nahum", "Habacuc",
    "Sofonias", "Ageo", "Zacarias", "Malakias", "Mateo",
    "Marcos", "Lucas", "Juan", "Mga Gawa", "Mga Taga-Roma",
    "1 Mga Taga-Corinto", "2 Mga Taga-Corinto", "Mga Taga-Galacia", "Mga Taga-Efeso", "Mga Taga-Filipos",
    "Mga Taga-Colosas", "1 Mga Taga-Tesalonica", "2 Mga Taga-Tesalonica", "1 Timoteo", "2 Timoteo",
    "Tito", "Filemon", "Mga Hebreo", "Santiago", "1 Pedro",
    "2 Pedro", "1 Juan", "2 Juan", "3 Juan", "Judas",
    "Pahayag"
  ],
  vi: [
    "Sáng Thế Ký", "Xuất Ê-díp-tô Ký", "Lê-vi Ký", "Dân Số Ký", "Phục Truyền Luật Lệ Ký",
    "Giô-suê", "Các Quan Xét", "Ru-tơ", "1 Sa-mu-ên", "2 Sa-mu-ên",
    "1 Các Vua", "2 Các Vua", "1 Sử Ký", "2 Sử Ký", "E-xơ-ra",
    "Nê-hê-mi", "Ê-xơ-tê", "Gióp", "Thánh Thi", "Châm Ngôn",
    "Truyền Đạo", "Nhã Ca", "Ê-sai", "Giê-rê-mi", "Ca Thương",
    "Ê-xê-chi-ên", "Đa-ni-ên", "Ô-sê", "Giô-ên", "A-mốt",
    "Áp-đia", "Giô-na", "Mi-chê", "Na-hum", "Ha-ba-cúc",
    "Sô-phô-ni", "Ha-gai", "Xa-cha-ri", "Ma-la-chi", "Ma-thi-ơ",
    "Mác", "Lu-ca", "Giăng", "Công Vụ Các Sứ Đồ", "Rô-ma",
    "1 Cô-rinh-tô", "2 Cô-rinh-tô", "Ga-la-ti", "Ê-phê-sô", "Phi-líp",
    "Cô-lô-se", "1 Tê-sa-lô-ni-ca", "2 Tê-sa-lô-ni-ca", "1 Ti-mô-thê", "2 Ti-mô-thê",
    "Tít", "Phi-lê-môn", "Hê-bơ-rơ", "Gia-cơ", "1 Phi-e-rơ",
    "2 Phi-e-rơ", "1 Giăng", "2 Giăng", "3 Giăng", "Giu-đe",
    "Khải Huyền"
  ],
  zh: [
    "创世记", "出埃及记", "利未记", "民数记", "申命记",
    "约书亚记", "士师记", "路得记", "撒母耳记上", "撒母耳记下",
    "列王纪上", "列王纪下", "历代志上", "历代志下", "以斯拉记",
    "尼希米记", "以斯帖记", "约伯记", "诗篇", "箴言",
    "传道书", "雅歌", "以赛亚书", "耶利米书", "耶利米哀歌",
    "以西结书", "但以理书", "何西阿书", "约珥书", "阿摩司书",
    "俄巴底亚书", "约拿书", "弥迦书", "那鸿书", "哈巴谷书",
    "西番雅书", "哈该书", "撒迦利亚书", "玛拉基书", "马太福音",
    "马可福音", "路加福音", "约翰福音", "使徒行传", "罗马书",
    "哥林多前书", "哥林多后书", "加拉太书", "以弗所书", "腓立比书",
    "歌罗西书", "帖撒罗尼迦前书", "帖撒罗尼迦后书", "提摩太前书", "提摩太后书",
    "提多书", "腓利门书", "希伯来书", "雅各书", "彼得前书",
    "彼得后书", "约翰一书", "约翰二书", "约翰三书", "犹大书",
    "启示录"
  ]
};

export default localizedBooks;
