export const englishVersionNames: Record<string, string> = {
  akjv: "American King James Version",
  amp: "Amplified Bible",
  ampc: "Amplified Bible (Classic)",
  asv: "American Standard Version",
  brg: "BRG Bible",
  ceb: "Common English Bible",
  cev: "Contemporary English Version",
  cevd: "CEV (Deuterocanon)",
  cjb: "Complete Jewish Bible",
  csb: "Christian Standard Bible",
  darby: "Darby Translation",
  dlnt: "Disciples' Literal New Testament",
  dra: "Douay-Rheims 1899 American",
  ehv: "EHV",
  erv: "Easy-to-Read Version",
  esv: "English Standard Version",
  exb: "Expanded Bible",
  gnt: "Good News Translation",
  gnv: "1599 Geneva Bible",
  gw: "God's Word Translation",
  hcsb: "Holman Christian Standard Bible",
  icb: "International Children's Bible",
  isv: "International Standard Version",
  jub: "Jubilee Bible 2000",
  kj21: "21st Century King James Version",
  kjv: "King James Version",
  leb: "Lexham English Bible",
  mev: "Modern English Version",
  mounce: "Mounce Reverse-Interlinear NT",
  msg: "The Message",
  nabre: "New American Bible (Revised)",
  nasb: "New American Standard Bible",
  ncv: "New Century Version",
  net: "NET Bible",
  nirv: "New International Reader's Version",
  niv1984: "New International Version (1984)",
  niv2011: "New International Version (2011)",
  nivuk: "New International Version (UK)",
  nkjv: "New King James Version",
  nlt: "New Living Translation",
  nlt2013: "New Living Translation (2013)",
  nlv: "New Life Version",
  nog: "Names of God Bible",
  nrsv: "New Revised Standard Version",
  nrsva: "New Revised Standard Version (Ang)",
  ojb: "Orthodox Jewish Bible",
  phillips: "Phillips Translation",
  rsv: "Revised Standard Version",
  rsvce: "Revised Standard Version (CE)",
  tlb: "The Living Bible",
  tlv: "Tree of Life Version",
  voice: "The Voice",
  web: "World English Bible",
  webbe: "World English Bible (British)",
  wyc: "Wycliffe Bible",
  ylt: "Young's Literal Translation"
};

export const englishCopyrights: Record<string, string> = {
  akjv: "American King James Version (AKJV) is in the public domain.",
  amp: "Scripture quotations taken from the Amplified® Bible, Copyright © 2015 by The Lockman Foundation. Used by permission.",
  ampc: "Scripture quotations taken from the Amplified® Bible (Classic), Copyright © 1954, 1958, 1962, 1964, 1965, 1987 by The Lockman Foundation. Used by permission.",
  asv: "American Standard Version (ASV) is in the public domain.",
  brg: "BRG Bible is in the public domain.",
  ceb: "Scripture quotations from the Common English Bible, Copyright © 2011 Common English Bible. Used by permission.",
  cev: "Scripture quotations from the Contemporary English Version, Copyright © 1995 American Bible Society. Used by permission.",
  cevd: "Scripture quotations from the Contemporary English Version, Copyright © 1995 American Bible Society. Used by permission.",
  cjb: "Scripture quotations from the Complete Jewish Bible, Copyright © 1998 by David H. Stern. Used by permission.",
  csb: "Scripture quotations from the Christian Standard Bible®, Copyright © 2017 by Holman Bible Publishers. Used by permission.",
  darby: "Darby Translation (DARBY) is in the public domain.",
  dlnt: "Disciples' Literal New Testament, Copyright © 2011 by Michael J. Magill. Used by permission.",
  dra: "Douay-Rheims 1899 American Edition (DRA) is in the public domain.",
  ehv: "Scripture quotations from the Evangelical Heritage Version, Copyright © 2019 Warburg Project. Used by permission.",
  erv: "Scripture quotations from the Easy-to-Read Version, Copyright © 2006 by Bible League International. Used by permission.",
  esv: "Scripture quotations are from The ESV® Bible (The Holy Bible, English Standard Version®), copyright © 2001 by Crossway, a publishing ministry of Good News Publishers. Used by permission. All rights reserved.",
  exb: "Scripture quotations from The Expanded Bible, Copyright © 2011 by Thomas Nelson. Used by permission.",
  gnt: "Scripture quotations from the Good News Translation, Copyright © 1992 by American Bible Society. Used by permission.",
  gnv: "1599 Geneva Bible (GNV) is in the public domain.",
  gw: "Scripture quotations from GOD'S WORD® Translation, Copyright © 1995 by God's Word to the Nations. Used by permission.",
  hcsb: "Scripture quotations from the Holman Christian Standard Bible®, Copyright © 1999, 2000, 2002, 2003, 2009 by Holman Bible Publishers. Used by permission.",
  icb: "Scripture quotations from the International Children's Bible®, Copyright © 1986, 1988, 1999 by Thomas Nelson. Used by permission.",
  isv: "Scripture quotations from the International Standard Version, Copyright © 1995-2014 by ISV Foundation. Used by permission.",
  jub: "Jubilee Bible 2000 (JUB) is in the public domain.",
  kj21: "21st Century King James Version (KJ21), Copyright © 1994 by Deuel Enterprises. Used by permission.",
  kjv: "King James Version (KJV) is in the public domain.",
  leb: "Scripture quotations from the Lexham English Bible, Copyright © 2012 Logos Bible Software. Used by permission.",
  mev: "Scripture quotations from the Modern English Version, Copyright © 2014 by Military Bible Association. Used by permission.",
  mounce: "Scripture quotations from Mounce Reverse-Interlinear NT, Copyright © 2011 by William D. Mounce. Used by permission.",
  msg: "The Message (MSG) Copyright © 1993, 1994, 1995, 1996, 2000, 2001, 2002. Used by permission of NavPress Publishing Group.",
  nabre: "Scripture quotations from the New American Bible (Revised Edition), © 2010, 1991, 1986, 1970 Confraternity of Christian Doctrine. Used by permission.",
  nasb: "Scripture taken from the NEW AMERICAN STANDARD BIBLE®, Copyright © 1960, 1962, 1963, 1968, 1971, 1972, 1973, 1975, 1977, 1995 by The Lockman Foundation. Used by permission.",
  ncv: "Scripture quotations from the New Century Version®, Copyright © 2005 by Thomas Nelson. Used by permission.",
  net: "Scripture quotations from the NET Bible®, Copyright © 1996-2016 by Biblical Studies Press. Used by permission.",
  nirv: "Scripture quotations from the New International Reader's Version®, Copyright © 1995, 1996, 1998, 2014 by Biblica, Inc. Used by permission.",
  niv1984: "Holy Bible, New International Version®, NIV® Copyright © 1973, 1978, 1984 by Biblica, Inc.® Used by permission. All rights reserved worldwide.",
  niv2011: "Holy Bible, New International Version®, NIV® Copyright © 1973, 1978, 1984, 2011 by Biblica, Inc.® Used by permission. All rights reserved worldwide.",
  nivuk: "Holy Bible, New International Version®, NIV® Copyright © 1973, 1978, 1984, 2011 by Biblica, Inc.® Used by permission. All rights reserved worldwide.",
  nkjv: "Scripture quotations from the New King James Version®, Copyright © 1982 by Thomas Nelson. Used by permission.",
  nlt: "Scripture quotations from the Holy Bible, New Living Translation®, Copyright © 1996, 2004, 2015 by Tyndale House Foundation. Used by permission.",
  nlt2013: "Scripture quotations from the Holy Bible, New Living Translation®, Copyright © 1996, 2004, 2013 by Tyndale House Foundation. Used by permission.",
  nlv: "Scripture quotations from the New Life Version, Copyright © 1969 by Christian Literature International. Used by permission.",
  nog: "Scripture quotations from The Names of God Bible, Copyright © 2011 by Baker Publishing Group. Used by permission.",
  nrsv: "New Revised Standard Version Bible, copyright © 1989 the Division of Christian Education of the National Council of the Churches of Christ in the United States of America. Used by permission. All rights reserved.",
  nrsva: "New Revised Standard Version Bible, copyright © 1989 the Division of Christian Education of the National Council of the Churches of Christ in the United States of America. Used by permission. All rights reserved.",
  ojb: "Orthodox Jewish Bible, Copyright © 2002, 2003, 2008, 2010, 2011 by Artists for Israel International. Used by permission.",
  phillips: "Scripture quotations from the Phillips Translation, Copyright © 1960, 1986 by J.B. Phillips. Used by permission.",
  rsv: "Revised Standard Version (RSV) is in the public domain.",
  rsvce: "Revised Standard Version Catholic Edition (RSVCE), Copyright © 1965, 1966 by Division of Christian Education of the National Council of the Churches of Christ. Used by permission.",
  tlb: "Scripture quotations from The Living Bible, Copyright © 1971 by Tyndale House Foundation. Used by permission.",
  tlv: "Scripture quotations from the Tree of Life Version, Copyright © 2015 by the Messianic Jewish Family Bible Society. Used by permission.",
  voice: "Scripture quotations from The Voice™, Copyright © 2012 by Ecclesia Bible Society. Used by permission.",
  web: "World English Bible (WEB) is in the public domain.",
  webbe: "World English Bible British Edition (WEBBE) is in the public domain.",
  wyc: "Wycliffe Bible (WYC) is in the public domain.",
  ylt: "Young's Literal Translation (YLT) is in the public domain."
};
